import { Header } from "@/components/molecules";
import { Hero } from "@/components/molecules/hero";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>GAME LORD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <div className="pt-12">
        <Hero />
      </div>
    </>
  );
}
