import { Header } from "@/components/molecules";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>GAME LORD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <div className={"flex items-center justify-center h-screen flex-col"}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <p className={"font-anton text-7xl"}>junel sacro</p>
      </div>
    </>
  );
}
